version: 2

models:
  - name: stg_github
    description: "Columns description source: https://github.com/igrigorik/gharchive.org/blob/master/bigquery/schema.js"
    columns:
      - name: _pk
        description: "Unique IDs of events- Primary Key. What are events-https://www.sumologic.com/blog/a-beginners-guide-to-github-events/"
        tests:
          - unique
          - not_null

      - name: type
        description: "Type of used notification system that allows you to interact with your GitHub repo."

      - name: is_public
        description: "Always true since only public activity is recorded."

      - name: repo_id
        description: "Numeric ID of the GitHub repository"

      - name: repo_name
        description: "Repository name"

      - name: repo_url
        description: "Repository URL"

      - name: actor_id
        description: "Numeric ID of the GitHub actor"

      - name: actor_login
        description: "Actor's GitHub login"

      - name: actor_gravatar_id
        description: "Actor's Gravatar ID"

      - name: actor_avatar_url
        description: "Actor's Gravatar URL"

      - name: actor_url
        description: "Actor's profile URL"

      - name: org_id
        description: "Numeric ID of the GitHub org"

      - name: org_login
        description: "Org's GitHub login"

      - name: org_gravatar_id
        description: "Org's Gravatar ID"

      - name: org_avatar_url
        description: "Org's Gravatar URL"

      - name: org_url
        description: "Org's profile URL"

      - name: created_at_datetime_utc
        description: "Timestamp of associated event"

      - name: id
        description: "Unique event ID"

      - name: other
        description: "Unknown fields in JSON format"